### ISSUE TITLE
Using without configuration file

### ISSUE THREAD

**Issue by buzzard10** [msztorc/php-dpd-api#5]
Is it possible to define all params directly in script without using configuration file? I want to use this package in different project and it'll be hard to define config file

**Comment by msztorc** [comment]
yes, you can pass configuration directly to the DPDService constructor, like below:


`$dpd = new DPDService($fid, $username, $password, $wsdl, $lang);`

for instance:

```
$dpd = new DPDService(
    '1234', //fid
    'testuser', //user
    'paSswOrD', //password
    'https://dpdservicesdemo.dpd.com.pl/DPDPackageObjServicesService/DPDPackageObjServices?WSDL', //wsdl
    'PL' //lang
);
```

Hope this helps!

**Comment by buzzard10** [comment]
Thank you man! Great work!
